language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
env:
  - PHANTOMJS_VERSION="1.9.1"
  - PHANTOMJS_VERSION="1.9.2"

install:
  # Install Graphics Magick dependency
  - sudo apt-get install graphicsmagick -y

  # Run phantomjs install script
  - ./src-test/install_phantomjs.sh

  # Install node_modules
  - npm install
before_script:
  - npm install grunt-cli
script:
  - npm test

notifications:
  email: false
